name: ENVIRONMENT VARIABLES 
on: workflow_dispatch
env:
  APP_ENV: "dev"
jobs:
  env-demo:
    env:
      APP_ENV: "test"
    runs-on: ubuntu-latest
    steps:
      - name: connecting to dev
        run: echo "app is connceting to $APP_ENV"
