name: Build & deploy 
on:
  pull_request: 
    types:
      - opened
      - synchronize
jobs:
   builds:
     runs-on: ubuntu-latest
     steps:
       - name: Build step
         run: echo "Building the appliacation"
      
