name: build & deploy 
on:
  push:
    branches: 
      - main
  pull_request: 
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Build steps
      run: echo "Building the appliaction"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step
        run: echo "Deploying the application" 
