name: github_context
on: workflow_dispatch
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: use context varaibles 
        run: |
          echo "This workflow ins triggred by ${{ github.actor }}"
          echo "the repo name is ${{ github.repository }}"
          echo "the github branch name is ${{github.ref_name }}"
          
      - name: get the full context 
        run: echo "${{ toJson(github) }}" 

      - name: print environamt 
        run: echo "$GITHUB_SHA"
        
