name: if-demo
on: 
  push:
    branches:
      - main
      - develop
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: run if branch is main
        if: github.ref_name == 'main' 
        run: echo "running the main branch"

      -  name: Run this step
         run: echo "Running thi step"
         
