name: inputs Demo
on:
  workflow_dispatch: 
    inputs:
      environment: 
        description: choose the envirionment to deploy default
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod
      artificats_version:
        description: give the description tag 
        required: true
jobs:
  inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        run: echo "Deploying the ${{ inputs.artificats_version }} appliaction to ${{ inputs.environment }}"
        
        
        
