name: or condition 
on: push 
jobs:
  or-condition:
    runs-on: ubuntu-latest
    steps:
      - name: run a ragu321 or raghu
        if: github.actor == 'Ragu321' || 'raghavendrareddy bn'
        run: echo " it is generetd either by ragu 321 or raghu
